src/DotNetFlow/Controllers/SessionController.cs
using System.Web.Mvc;
using System.Web.Security;
using DotNetFlow.Core.Commands;
using DotNetFlow.Core.ReadModel.Models;
using DotNetFlow.Core.Services;
using DotNetFlow.Extensions;

namespace DotNetFlow.Controllers
{
    /// <summary>
    /// Handles log-in and log-out functionality
    /// </summary>
    public class SessionController : Controller
    {
        private readonly IAuthenticationService _authentication;

        public SessionController(IAuthenticationService authentication)
        {
            _authentication = authentication;
        }

        //
        // GET: /login

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /login

        /// <summary>
        /// Create a new session (login user when correct credentials entered)
        /// </summary>
        /// <param name="command"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(LoginUserCommand command)
        {
            if (ModelState.IsValid)
            {
                var authorisation = _authentication.Authenticate(command.UsernameOrEmail, command.Password);
                if (authorisation.IsAuthenticated)
                {
                    LoginUser(authorisation.User);
                    return RedirectToRoute("Home");   
                }

                ModelState.AddModelError("*", "Login failed, please check your username or e-mail address and password and try again.");
            }

            return View();
        }

        private static void LoginUser(UserAccountModel user)
        {
            FormsAuthentication.SetAuthCookie(user.Username, true);
        }

        //
        // GET: /logout
 
        public ActionResult Delete()
        {
            return View();
        }

        //
        // POST: /logout

        [HttpPost]
        public ActionResult Delete(FormCollection collection)
        {
            FormsAuthentication.SignOut();
            return Redirect(Url.Home());
        }
    }
}

src/DotNetFlow/Views/Session/Create.cshtml
@model DotNetFlow.Core.Commands.LoginUserCommand
@{ ViewBag.Title = "Login"; }
       
<h1 class="page_head">Sign In</h1>    
<div class="breadcrumbs"></div>

<div class="login_form">
    <div class="login_content">
        <p>Enter the email address and password you used to register on the site.</p>
    </div>
    
    @using (Html.BeginForm("Create", "Session", FormMethod.Post, new { id = "loginform" }))
    {
        @Html.ValidationSummary(true)

        <div class="form_row clearfix">
            @Html.LabelFor(model => model.UsernameOrEmail, "Username or E-mail")
	        @Html.EditorFor(model => model.UsernameOrEmail)
            @Html.ValidationMessageFor(model => model.UsernameOrEmail)
        </div>

        <div class="form_row clearfix">
            @Html.LabelFor(model => model.Password, "Password")
	        @Html.PasswordFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <p class="rember">
            <input name="rememberme" type="checkbox" id="rememberme" value="forever" class="fl" /> Remember me on this computer
        </p>
        
        <p>
            <input class="btn_input_highlight btn_spacer" type="submit" value="Sign In"  name="submit" />
            @Html.ValidationMessage("*")
        </p>

        <p class="links">
            <a href="@Url.RouteUrl("Register")">New User? Register Now</a> | <a href="">Forgot Password?</a> 
        </p>
    }
</div>

@section JavaScript {
    <script type="text/javascript">
        $(function () {
            $('#content form :input').addClass('textfield');
            $('#content form .input-validation-error:visible:first, #content form :input:visible:first').focus();
        });
    </script>
}

src/DotNetFlow/Views/Session/Delete.cshtml
@{ ViewBag.Title = "Logout"; }
       
<h1 class="page_head">Sign Out</h1>    
<div class="breadcrumbs"></div>

<div class="login_form">
    <div class="login_content">
        <p>Are you sure you want to logout?</p>
    </div>
    
    @using (Html.BeginForm())
    {
        <p>
            <input class="btn_input_highlight btn_spacer" type="submit" value="Log Out"  name="submit" />
        </p>
    }
</div>